diyblog/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length
from diyblog.models import User

class BlogCreateForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=200)])
    author = SelectField('Author', coerce=int)
    content = TextAreaField('Content', validators=[DataRequired(), Length(max=2000)])
    post_date = DateField('Post Date', validators=[DataRequired()])

class BlogCommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[DataRequired(), Length(max=1000)])

diyblog/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog', template_folder='templates')

from . import views

diyblog/blog/views.py
from flask import render_template, redirect, url_for
from flask_login import current_user, login_required
from . import bp
from .forms import BlogCreateForm, BlogCommentForm
from diyblog.models import User, BlogPost, BlogComment
from diyblog import db


@bp.route('/')
def index():
    num_authors = User.query.count()
    num_posts = BlogPost.query.count()
    num_comments = BlogComment.query.count()

    stats = {
        'num_authors': num_authors,
        'num_posts': num_posts,
        'num_comments': num_comments
    }

    return render_template('blog/index.html', stats=stats)

@bp.route('/create', methods=['GET', 'POST'])
def create_post():
    form = BlogCreateForm()
    form.author.choices = [(u.id, u.username) for u in User.query.order_by('username')]

    if form.validate_on_submit():
        blog_post = BlogPost(name=form.name.data, author_id=form.author.data, \
            content=form.content.data, post_date=form.post_date.data)
        db.session.add(blog_post)
        db.session.commit()
        return redirect(url_for('blog.index'))
    return render_template('blog/create.html', form=form)

@bp.route('/blogs')
def blog_list():
    blogs = BlogPost.query.all()

    return render_template('blog/list_blogs.html', blogs=blogs)

@bp.route('/<int:blog_id>')
def blog_detail(blog_id):
    blog = BlogPost.query.filter_by(id=blog_id).first()
    blog_comments = BlogComment.query.filter_by(blog_id=blog_id).all()

    return render_template('blog/detail_blog.html', blog=blog, blog_comments=blog_comments)

@bp.route('/bloggers')
def blog_author_list():
    authors = User.query.all()

    return render_template('blog/list_authors.html', authors=authors)

@bp.route('/blogger/<int:blogger_id>')
def blog_author_detail(blogger_id):
    author = User.query.filter_by(id=blogger_id).first()
    author_blogs = BlogPost.query.filter_by(author_id=author.id)

    return render_template('blog/detail_author.html', author=author, author_blogs=author_blogs)

@bp.route('/<int:blog_id>/create', methods=['GET', 'POST'])
@login_required
def comment(blog_id):
    form = BlogCommentForm()

    if form.validate_on_submit():
        comment = BlogComment(comment=form.comment.data, author_id=current_user.id, blog_id=blog_id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('blog.blog_detail', blog_id=blog_id))
    
    return render_template('blog/comment.html', form=form)

diyblog/blog/templates/blog/comment.html
{% extends "base.html" %}

{% block content %}
    <h1>Add a comment</h1>
    <form method="post">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.comment.label }}
            {{ form.comment(class_='form-control', rows=10) }}
        </div>
        {% if form.comment.errors %}
            {% for error in form.author.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

diyblog/blog/templates/blog/create.html
{% extends "base.html" %}

{% block content %}
    <h1>New Blog Post</h1>
    <hr>
    <form method="post">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class_='form-control') }}
        </div>
        {% if form.name.errors %}
            {% for error in form.name.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            {{ form.author.label }}
            {{ form.author(class_='form-control') }}
        </div>
        {% if form.author.errors %}
            {% for error in form.author.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            {{ form.post_date.label }}
            {{ form.post_date(class_='form-control') }}
        </div>
        {% if form.post_date.errors %}
            {% for error in post_date.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="form-group">
            {{ form.content.label }}
            {{ form.content(class_='form-control', rows=10) }}
        </div>
        {% if form.content.errors %}
            {% for error in form.content.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

diyblog/blog/templates/blog/detail_author.html
{% extends "base.html" %}

{% block content %}
    {% if author %}
        <h1>Blogger: {{ author.username }}</h1>
        <h4>Bio</h4>
        {{ author.bio }}
        <h4>Blogs list</h4>
        <ul>
            {% for blog in author_blogs %}
                <li>
                    <a href="{{ url_for('blog.blog_detail', blog_id=blog.id) }}">{{ blog.name }}</a> ({{ blog.post_date.strftime('%b. %d, %Y') }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>That blogger doesn't exist!</p>
    {% endif %}
{% endblock %}

diyblog/blog/templates/blog/detail_blog.html
{% extends "base.html" %}

{% block content %}
    {% if blog %}
        <h1>{{ blog.name }}</h1>
        <strong>Post Date: </strong>{{ blog.post_date.strftime('%b. %d, %Y')}}
        <br>
        <strong>Author: </strong><a href="{{ url_for('blog.blog_author_detail', blogger_id=blog.author.id) }}">{{ blog.author.username }}</a>
        <br>
        <strong>Description:</strong>
        <br>
        {{ blog.content }}
        <br>
        <h4>Comments</h4>
        <hr>
        {% for comment in blog_comments %}
            <div>{{ comment.author.username }} ({{ comment.post_date }}) - {{ comment.comment }}</div>
            <hr>
        {% endfor %}
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('blog.comment', blog_id=blog.id) }}">Add new comment</a>
        {% else %}
            <a href="{{ url_for('user.login', next=request.path) }}">Login</a> to add a comment.
        {% endif %}
    {% else %}
        <p>The blog doesn't exist</p>
    {% endif %}
{% endblock %}

diyblog/blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to my blog</h1>
    <p>
        This was created to try and recreate the Mozilla Developer Network Django assessment using Flask.  The assement can be found
        <a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">here</a>.
        <br />
        Here are some simple statistics about this blog.
    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Statistic Type</th>
                <th scope="col">Count</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Number of Bloggers</td>
                <td>{{ stats.num_authors }}</td>
            </tr>
            <tr>
                <td>Number of Blog posts</td>
                <td>{{ stats.num_posts }}</td>
            </tr>
            <tr>
                <td>Number of Comments</td>
                <td>{{ stats.num_comments }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}

diyblog/blog/templates/blog/list_authors.html
{% extends "base.html" %}

{% block content %}
    <h1>Bloggers</h1>

    {% if authors %}
        <ul>
            {% for author in authors %}
                <li>
                    <a href="{{ url_for('blog.blog_author_detail', blogger_id=author.id) }}">{{ author.username }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no bloggers!</p>
    {% endif %}
{% endblock %}

diyblog/blog/templates/blog/list_blogs.html
{% extends "base.html" %}

{% block content %}
    <h1>Blog List</h1>
    {% if blogs %}
        <ul>
            {% for blog in blogs %}
                <li>
                    <a href="{{ url_for('blog.blog_detail', blog_id=blog.id) }}">{{ blog.name }}</a> ({{ blog.post_date.strftime('%b. %d, %Y')}}) -- {{ blog.author.username }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are not any blog posts yet</p>
    {% endif %}
{% endblock %}