diyblog/models.py
from datetime import datetime
from flask_user import UserMixin
from diyblog import db


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

    # User authentication fields
    username = db.Column(db.String(50), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)

    # User fields
    active = db.Column(db.Boolean())
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    bio = db.Column(db.String(400))

    roles = db.relationship('Role', secondary='user_roles', backref='roles')


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), unique=True)


class UserRoles(db.Model):
    __tablename__ = 'user_roles'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))


class BlogPost(db.Model):
    __tablename__ = 'blog_posts'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(200))
    author = db.relationship('User')
    author_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    content = db.Column(db.String(2000))
    post_date = db.Column(db.DateTime, default=datetime.utcnow)


class BlogComment(db.Model):
    __tablename__ = 'blog_comments'
    id = db.Column(db.Integer(), primary_key=True)
    comment = db.Column(db.String(1000))
    author_id = db.Column(db.Integer(), db.ForeignKey('users.id'))
    author = db.relationship('User')
    post_date = db.Column(db.DateTime(), default=datetime.utcnow)
    blog_id = db.Column(db.Integer(), db.ForeignKey('blog_posts.id'))
    blog = db.relationship('BlogPost', cascade='delete')

diyblog/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length
from diyblog.models import User

class BlogCreateForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=200)])
    author = SelectField('Author', coerce=int)
    content = TextAreaField('Content', validators=[DataRequired(), Length(max=2000)])
    post_date = DateField('Post Date', validators=[DataRequired()])

class BlogCommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[DataRequired(), Length(max=1000)])

diyblog/__init__.py
from flask import Flask, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_user import UserManager
from diyblog.config import Config

db = SQLAlchemy()
migrate = Migrate()

def create_app(test_config=None):
    from . import blog
    from . import models

    app = Flask(__name__)
    
    if test_config is None:
        app.config.from_object(Config)
    else:
        app.config.from_mapping(test_config)

    db.init_app(app)
    migrate.init_app(app, db)
    user_manager = UserManager(app, db, models.User)

    app.register_blueprint(blog.bp)

    @app.route('/')
    def index():
        return redirect(url_for('blog.index'))

    return app

diyblog/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__, url_prefix='/blog', template_folder='templates')

from . import views

diyblog/blog/views.py
from flask import render_template, redirect, url_for
from flask_login import current_user, login_required
from . import bp
from .forms import BlogCreateForm, BlogCommentForm
from diyblog.models import User, BlogPost, BlogComment
from diyblog import db


@bp.route('/')
def index():
    num_authors = User.query.count()
    num_posts = BlogPost.query.count()
    num_comments = BlogComment.query.count()

    stats = {
        'num_authors': num_authors,
        'num_posts': num_posts,
        'num_comments': num_comments
    }

    return render_template('blog/index.html', stats=stats)

@bp.route('/create', methods=['GET', 'POST'])
def create_post():
    form = BlogCreateForm()
    form.author.choices = [(u.id, u.username) for u in User.query.order_by('username')]

    if form.validate_on_submit():
        blog_post = BlogPost(name=form.name.data, author_id=form.author.data, \
            content=form.content.data, post_date=form.post_date.data)
        db.session.add(blog_post)
        db.session.commit()
        return redirect(url_for('blog.index'))
    return render_template('blog/create.html', form=form)

@bp.route('/blogs')
def blog_list():
    blogs = BlogPost.query.all()

    return render_template('blog/list_blogs.html', blogs=blogs)

@bp.route('/<int:blog_id>')
def blog_detail(blog_id):
    blog = BlogPost.query.filter_by(id=blog_id).first()
    blog_comments = BlogComment.query.filter_by(blog_id=blog_id).all()

    return render_template('blog/detail_blog.html', blog=blog, blog_comments=blog_comments)

@bp.route('/bloggers')
def blog_author_list():
    authors = User.query.all()

    return render_template('blog/list_authors.html', authors=authors)

@bp.route('/blogger/<int:blogger_id>')
def blog_author_detail(blogger_id):
    author = User.query.filter_by(id=blogger_id).first()
    author_blogs = BlogPost.query.filter_by(author_id=author.id)

    return render_template('blog/detail_author.html', author=author, author_blogs=author_blogs)

@bp.route('/<int:blog_id>/create', methods=['GET', 'POST'])
@login_required
def comment(blog_id):
    form = BlogCommentForm()

    if form.validate_on_submit():
        comment = BlogComment(comment=form.comment.data, author_id=current_user.id, blog_id=blog_id)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('blog.blog_detail', blog_id=blog_id))
    
    return render_template('blog/comment.html', form=form)

diyblog/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>DIY Blog Flask</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <nav>
                    <a class="nav-link" href="{{ url_for('blog.index') }}">Home</a>
                    <a class="nav-link" href="{{ url_for('blog.blog_list') }}">All Blogs</a>
                    <a class="nav-link" href="{{ url_for('blog.blog_author_list') }}">All Bloggers</a>
                </nav>
                <br>
                <nav>
                    {% if current_user.is_authenticated %}
                        <a class="nav-link">{{ current_user.username }}</a>
                        <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{{ url_for('user.login', next=request.path) }}">Login</a>
                    {% endif %}
                </nav>
                <br>
            </div>
            <div class="col-sm-10">
                {% block content %}{% endblock %}                
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>